include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    unnecessary_this: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    deprecated_member_use: ignore
    invalid_annotation_target: ignore
